// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kpn-LXWtCVvqj9qt8KIN8z8fpwa2W0w',
    appId: '1:663948094142:android:b88b9f8e3b698e5a970cef',
    messagingSenderId: '663948094142',
    projectId: 'mr-sami-elmallah',
    storageBucket: 'mr-sami-elmallah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvtxiK89Pb_59j209PODna59GN8SqiyR0',
    appId: '1:663948094142:ios:50feb6953a4ea1d5970cef',
    messagingSenderId: '663948094142',
    projectId: 'mr-sami-elmallah',
    storageBucket: 'mr-sami-elmallah.firebasestorage.app',
    androidClientId: '663948094142-8lqt5c8p9qdfcrtst141uak2n626seus.apps.googleusercontent.com',
    iosClientId: '663948094142-a5gs1tkp6rhc0ak0u1ps32og2vfvp31c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrSamyElmalah',
  );

}